### ISSUE TITLE
manual error

### ISSUE THREAD

**Issue by vivivum** [IAA-InvCodes/C-MILOS#4]
Device and OS : OSX 10.13 

Steps to reproduce : Segun manual, los datos de entrada por defecto deben estar organizados como [ x, y, lambda, Stokes ], pudiéndose indicar con entradas CTYPE en cabecera de ﬁts. Si no, el inversor encontrará el orden basándose en que la dimensión de tamaño 4 es Stokes, la siguiente mayor es lambda y las dos más grandes x, y.

Cuando se proporciona de entrada dato con el orden por defecto no funciona, con o sin keywords CTYPE en la cabecera.

Expected result : lectura de datos de entrada al inversor y funcionamiento normal

Actual result : salida del programa sin correr con error:

ERROR: the datatype of FITS spectro image must be FLOAT

Solution : re-organizar datos de entrada en orden [ lambda, Stokes, x, y ]

**Comment by Luis-Bellot** [comment]
Good catch! Manual and readme updated
